=== GeoVenezuela/geoserver-history/configuration/community-schema/featureTypes/SiteSamplingStatistics/ComplexDataStore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://www.geotools.org/complex"
  xmlns:c="http://www.geotools.org/complex" xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml">

  <import namespace="http://www.opengis.net/ogc" schemaLocation="http://schemas.opengis.net/filter/1.1.0/expr.xsd" />
  <import namespace="http://www.opengis.net/gml" 
  schemaLocation="http://schemas.opengis.net/gml/3.1.1/base/feature.xsd" />

  <element name="ComplexDataStore" type="c:ComplexDataStoreType" />

  <complexType name="ComplexDataStoreType">
    <sequence>
      <element name="sourceDataStores" type="c:sourceDataStoresPropertyType" />
      <element name="targetTypes" type="c:targetTypesPropertyType" />
      <element name="typeMappings" type="c:typeMappingsPropertyType" />
    </sequence>
  </complexType>

  <complexType name="sourceDataStoresPropertyType">
    <sequence>
      <element name="DataStore" minOccurs="0" maxOccurs="unbounded">
        <complexType>
          <sequence>
            <element name="id" type="string" />
            <element name="parameters">
              <complexType>
                <sequence>
                  <element name="Parameter" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                      <sequence>
                        <element name="name" type="string" />
                        <element name="value" type="string" />
                      </sequence>
                    </complexType>
                  </element>
                </sequence>
              </complexType>
            </element>
          </sequence>
          <attribute name="id" type="ID" />
        </complexType>
      </element>
    </sequence>
  </complexType>

  <complexType name="targetTypesPropertyType">
    <sequence>
      <element name="FeatureType" minOccurs="0" maxOccurs="1">
        <complexType>
          <sequence>
            <element name="schemaUri" type="string" />
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>

  <complexType name="typeMappingsPropertyType">
    <sequence>
      <element name="FeatureTypeMapping" minOccurs="0" maxOccurs="unbounded">
        <complexType>
          <sequence>
            <element name="sourceDataStore" type="string" />
            <element name="sourceType" type="string" />
            <element name="targetType" type="string" />
            <element name="groupBy" minOccurs="0" maxOccurs="1">
              <complexType>
                <sequence>
                  <element name="GroupByAttribute" type="string" minOccurs="0" maxOccurs="unbounded" />
                </sequence>
              </complexType>
            </element>
            <element name="fidMappings" minOccurs="0">
              <complexType>
                <sequence>
                  <element name="FidMapping" minOccurs="0" maxOccurs="unbounded" type="c:SingleMappingType" />
                </sequence>
              </complexType>
            </element>
            <element name="attributeMappings" minOccurs="0">
              <complexType>
                <sequence>
                  <element name="AttributeMapping" minOccurs="0" maxOccurs="unbounded" type="c:SingleMappingType" />
                </sequence>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>

  <complexType name="SingleMappingType">
    <sequence>
      <element name="isMultiple" type="boolean" minOccurs="0"/>
      <element name="targetAttribute" type="string" />
      <element name="sourceExpression">
        <complexType>
          <choice>
            <element name="OCQL" type="string" />
            <element name="Expression">
              <complexType>
                <sequence>
                  <element ref="ogc:expression" />
                </sequence>
              </complexType>
            </element>
          </choice>
        </complexType>
      </element>
    </sequence>
  </complexType>

</schema>

=== GeoVenezuela/geoserver-history/conf/data/featureTypes/complexWQ_Plus/wq_plus_mappings.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:ComplexDataStore xmlns:c="http://www.geotools.org/complex" xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.geotools.org/complex ComplexDataStore.xsd
                      http://www.opengis.net/ogc http://schemas.opengis.net/filter/1.1.0/expr.xsd">
  <sourceDataStores>
    <DataStore>
      <id>locationsXY</id>
      <parameters>
        <Parameter>
          <name>dbtype</name>
          <value>locationsxy</value>
        </Parameter>
        <Parameter>
          <name>user</name>
          <value>postgres</value>
        </Parameter>
        <Parameter>
          <name>passwd</name>
          <value>postgres</value>
        </Parameter>
        <Parameter>
          <name>host</name>
          <value>localhost</value>
        </Parameter>
        <Parameter>
          <name>port</name>
          <value>5432</value>
        </Parameter>
        <Parameter>
          <name>database</name>
          <value>sco</value>
        </Parameter>
        <Parameter>
          <name>driver</name>
          <value>org.geotools.data.geometryless.wrapper.PGConnectionPool</value>
        </Parameter>
        <Parameter>
          <name>urlprefix</name>
          <value>jdbc:postgresql://localhost:5432/sco</value>
        </Parameter>
        <Parameter>
          <name>geom_name</name>
          <value>location</value>
        </Parameter>
        <Parameter>
          <name>xcolumn</name>
          <value>x</value>
        </Parameter>
        <Parameter>
          <name>ycolumn</name>
          <value>y</value>
        </Parameter>
        <Parameter>
          <name>sqlView.1.typeName</name>
          <value>wq_derived</value>
        </Parameter>
        <Parameter>
          <name>sqlView.1.sqlQuery</name>
          <value>
            SELECT station_no, station_name as sitename,anzlic_no, project_no,
            sample_collection_date || determinand_code as id, sample_collection_date, determinand_description,
            results_value, longitude as x, -latitude as y FROM wq_ir_results WHERE 1=1 order by station_no
            </value>
        </Parameter>
      </parameters>
    </DataStore>
  </sourceDataStores>
  <targetTypes>
    <FeatureType>
      <schemaUri>wq_plus.xsd</schemaUri>
    </FeatureType>
  </targetTypes>
  <typeMappings>
    <FeatureTypeMapping>
      <sourceDataStore>locationsXY</sourceDataStore>
      <sourceType>wq_derived</sourceType>
      <targetType>wq_plus</targetType>
      <groupBy />
      <fidMappings>
        <FidMapping>
          <targetAttribute>wq_plus</targetAttribute>
          <sourceExpression>
            <OCQL>station_no</OCQL>
          </sourceExpression>
        </FidMapping>
        <FidMapping>
          <targetAttribute>wq_plus/measurement</targetAttribute>
          <sourceExpression>
            <OCQL>id</OCQL>
          </sourceExpression>
        </FidMapping>
      </fidMappings>
      <attributeMappings>
        <AttributeMapping>
          <targetAttribute>wq_plus/station_no</targetAttribute>
          <sourceExpression>
            <OCQL>station_no</OCQL>
          </sourceExpression>
        </AttributeMapping>
        <AttributeMapping>
          <targetAttribute>wq_plus/station_name</targetAttribute>
          <sourceExpression>
            <OCQL>sitename</OCQL>
          </sourceExpression>
        </AttributeMapping>
        <AttributeMapping>
          <targetAttribute>wq_plus/anzlic_no</targetAttribute>
          <sourceExpression>
            <OCQL>anzlic_no</OCQL>
          </sourceExpression>
        </AttributeMapping>
        <AttributeMapping>
          <targetAttribute>wq_plus/project_no</targetAttribute>
          <sourceExpression>
            <OCQL>project_no</OCQL>
          </sourceExpression>
        </AttributeMapping>
        <AttributeMapping>
          <targetAttribute>wq_plus/measurement</targetAttribute>
          <sourceExpression>
            <OCQL>null</OCQL>
          </sourceExpression>
        </AttributeMapping>
        <AttributeMapping>
          <targetAttribute>wq_plus/measurement/determinand_description</targetAttribute>
          <sourceExpression>
            <OCQL>determinand_description</OCQL>
          </sourceExpression>
        </AttributeMapping>
        <AttributeMapping>
          <targetAttribute>wq_plus/measurement/result</targetAttribute>
          <sourceExpression>
            <OCQL>result</OCQL>
          </sourceExpression>
        </AttributeMapping>
        <AttributeMapping>
          <targetAttribute>wq_plus/location</targetAttribute>
          <sourceExpression>
            <OCQL>location</OCQL>
          </sourceExpression>
        </AttributeMapping>
      </attributeMappings>
    </FeatureTypeMapping>
  </typeMappings>
</c:ComplexDataStore>
